### ISSUE TITLE
Hide menubar icon option

### ISSUE THREAD

**Issue by franzf** [archagon/sensible-side-buttons#1]
It would be nice to be able to hide the menubar icon and just leave the app working silently on the background. A similar utility, https://pilotmoon.com/scrollreverser/ has the option:

<img width="436" alt="screen shot 2017-07-11 at 23 07 09" src="https://user-images.githubusercontent.com/869168/28100052-d45b9260-668d-11e7-888a-58b4dd46f2b6.png">

**Comment by ddavidebor** [comment]
yeeees please got too many of them

**Comment by archagon** [comment]
Implemented.

**Comment by tenbeh5** [comment]
it is still not available. I cannot find hide menu bar icon option on the latest build.
