### ISSUE TITLE
Website doesn't use https and github doesn't include the .dmg

### ISSUE THREAD

**Issue by thearkadia** [archagon/sensible-side-buttons#10]
It's good practice to avoid downloading .dm'sg from sites without https to avoid a MITM that swaps the .dmg for a malicious one.

**Comment by archagon** [comment]
In fact, the .dmg is hosted on GH Pages, but [on a separate branch](https://github.com/archagon/sensible-side-buttons/blob/gh-pages/SensibleSideButtons-1.0.dmg). Unfortunately, GH Pages does not support HTTPS for custom domains, and I'm not a fan of the usual Cloudflare workaround.

**Comment by thearkadia** [comment]
Oh, why not include it in the main?

**Comment by bcongdon** [comment]
Pinging this issue, as [Github Pages now support HTTPS](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/)
