### ISSUE TITLE
Enable vertical scrolling

### ISSUE THREAD

**Issue by hieunc229** [archagon/sensible-side-buttons#12]
Thanks Alexei for this useful app. I have a question:
Is there any way to enable side buttons for vertical scrolling left and right?

Thank you!

**Comment by archagon** [comment]
You mean horizontal scrolling? Don't know if it helps, but you can scroll horizontally in macOS by holding Shift while using the scroll wheel.

**Comment by hieunc229** [comment]
Thanks @archagon, I did realized holding the Shift key would help.
