### ISSUE TITLE
Logitech M560 High Sierra Problems

### ISSUE THREAD

**Issue by Travelian** [archagon/sensible-side-buttons#13]
Hello there!

After trying to review comments through internet, I saw a comment from you in a M560 Logitech mouse having windows mouse events that makes behaviour on Mac very erratically.

I've tried installing the program in Mac with no success, with the keys behaviour unchanged.

If you want I can add as much information as you need to troubleshoot the issue.

Thank you!

**Comment by archagon** [comment]
Anyone else with High Sierra experiencing problems? I haven't had a chance to install it yet. It's possible there are breaking changes.

**Comment by Travelian** [comment]
As an update, I found out that it actually works... but not the buttons I wanted to function.

In M560 Logitech, the M4 and M5 I guess are assigned to the scroll left & right buttons, not the thumb ones.

So It's all about getting used to scroll back and forth with those buttons. I really wish this was configurable though.


Thank you once again for answering.

**Comment by archagon** [comment]
Is this adjustable in the Logitech mouse adjustment app?

**Comment by Travelian** [comment]
I tried to adjust stuff on Unifying software from logitech, but the program freezes and shows very buggy GUI. Also, from what I've read from logitech its not supposedly compatible with mac, only basic functionality, probably because of the event names of the thumb buttons (I dont know how to check this on mac).

**Comment by archagon** [comment]
Sorry, there's unfortunately not much I can do here. This is a Logitech problem. I've installed High Sierra on my machine and my existing mice work fine with the app.
