### ISSUE TITLE
Issue with Parallels Desktop

### ISSUE THREAD

**Issue by DiomedesDominguez** [archagon/sensible-side-buttons#23]
If I have the SSB enabled and try to use the buttons inside a virtual machine of Parallels Desktop it doesn't work; I have to disable it and them I can use my mouse as normally in Windows. If I have to use it again in Macintosh I have to re-enable it.

**Comment by archagon** [comment]
There's no easy way to fix this, unfortunately, since Parallels only
responds to M4/M5 and macOS only respond to the fake swipes generated by
SSB.
