### ISSUE TITLE
Interferes with Sky Go player

### ISSUE THREAD

**Issue by mdjmay4** [archagon/sensible-side-buttons#24]
When trying to run [Sky Go](https://en.wikipedia.org/wiki/Sky_Go), the player returns an error: `You appear to be running software capable of capturing video. If you want to watch this show, please ensure that all capture aoftware is disabled and try again. Code: PFE 9903.`

After quitting SensibleSideButtons, this error disappears

**Comment by archagon** [comment]
Does it still happen if you uncheck Enabled but don't quit the app?

I'm assuming Sky Go is overeagerly reacting to the event tap I'm using; not sure how to fix without some sort of blacklist.

**Comment by mdjmay4** [comment]
No, unchecking Enabled has no effect on this behaviour unfortunately.

**Comment by archagon** [comment]
I'm guessing Sky Go reacts to the "control[s] your computer" accessibility attribute of this app. Doubt it can be fixed.
