### ISSUE TITLE
Does Not Work With macOS Mojave

### ISSUE THREAD

**Issue by aquishix** [archagon/sensible-side-buttons#25]
Title says it all; Apple has made some change with Mojave that completely breaks this program.  Much sadness as a consequence.

**Comment by aquishix** [comment]
Actually, it does work -- but behaves slightly differently.  I distinctly recall that when I installed it on High Sierra, it worked out of the box.  I neither had to go into Accessibility settings to authorize it to control the machine, nor did I have to go up to the menu bar to enable it.  With Mojave, I had to do both.  The latter was completely unexpected, in particular.

**Comment by archagon** [comment]
Yeah, sorry — it’s a UI issue. I’ll try to fix it soon.

**Comment by keltoncrouse** [comment]
>it’s a UI issue

How so? Sorry, just curious. I get a popup upon launching asking me to enable accessibility settings, and then once I realized it wasn't working right away I just enabled it and it worked perfectly. 

It would, however, be better if it started enabled.
