### ISSUE TITLE
World of Warcraft

### ISSUE THREAD

**Issue by kswope** [archagon/sensible-side-buttons#26]
Not sure if this is still maintained but I'll file a semi-bug report

WoW is strange, its the only software I have on my mac that actually recognizes all the mouse buttons without any 3rd party software.  When setting up hotkeys you can click with the fourth mouse button and it will actually register it "mouse button 4"!

But the thing is, when this software is running, it doesn't register anything.  All I have to do is just uncheck it 'enabled' in the menu and WoW starts recognizing it again.

**Comment by archagon** [comment]
Unfortunately, there's no way around this unless I add a whitelist.
SensibleSideButtons intercepts M4 and M5, so any app that recognizes those
buttons natively will have to run without SSB enabled.

**Comment by kswope** [comment]
Right, a whitelist would probably work, but who knows if its worth it, and I wouldn't be up to the task.

Can WoW get away with doing this because using a trackpad with wow would be ridiculous so they can use those events anyway they want?

**Comment by archagon** [comment]
Actually, WoW isn't doing anything out of the ordinary—M4 and M5 are freely available for any app to use. I think most Source games will accept those buttons, too. Unfortunately, neither macOS nor the vast majority of apps make use of those buttons for navigation, hence my app.

**Comment by kswope** [comment]
So I can hassle any software makers to recognize m4 and m5 as 3 finger swipes (if they support 3 finger swipes) and they won't have any excuse?  Chrome browser for example.

**Comment by kallebornemark** [comment]
+1 for whitelist :)
