### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by alpha0010** [archagon/sensible-side-buttons#29]
I have been using this just fine for a few weeks now on High Sierra 10.13.6.  Then today I booted the machine, and the mouse navigation buttons do nothing.  Tried launching/relaunching/quitting the program, but nothing changes.

Any suggestions how to debug?

**Comment by hakanersu** [comment]
Did you enable it again?
<img width="375" alt="screen shot 2018-10-04 at 13 28 29" src="https://user-images.githubusercontent.com/1052467/46468589-7f28a180-c7d9-11e8-9cab-c96f14184e64.png">

After osx update, i had to enable again.

**Comment by alpha0010** [comment]
Yes, I did try disable/enabling it several times.  Maybe I will try updating the OS, see if that resolves the issue.

**Comment by chris-tse** [comment]
Are you on Mojave? I updated to Mojave and it no longer works.

**Comment by alpha0010** [comment]
OS updated, mouse navigation working again.
