### ISSUE TITLE
Menubar icon menu content disappearing

### ISSUE THREAD

**Issue by indrekpaas** [archagon/sensible-side-buttons#3]
First off—thank you for an amazing app!

Clicking on and off the menu bar icon seems to make some of the menu contents disappear.

<img width="354" alt="screen shot 2017-07-21 at 14 31 31" src="https://user-images.githubusercontent.com/6239035/28449298-f2f48c90-6e21-11e7-8b59-7676ab16837e.png">

Running on OS X 10.11.6.

**Comment by archagon** [comment]
Hmm, weird. Doesn't happen on my 10.12 — might be a 10.11 issue. Well, in any case, there's nothing important in that spot, just the app credits!

**Comment by indrekpaas** [comment]
For what it's worth, the issue persists after restarting the app—the content depicted is permanently missing.

**Comment by archagon** [comment]
Closing b/c it seems to only affect older macOS versions and I don't have the time to test & fix.
