### ISSUE TITLE
What's the meaning of "Trigger on Mouse Down"

### ISSUE THREAD

**Issue by yingbo** [archagon/sensible-side-buttons#38]
Selecting it or not, I cannot tell any differences.

**Comment by mikroskeem** [comment]
Trigger on Mouse Down means that keycodes are sent out immediately on pressing the button, instead of waiting until button gets released (Mouse Up). To tell difference better, try holding the button down a bit longer while this option is off. Now turn that option on and see the difference.

**Comment by yingbo** [comment]
Thank you, @mikroskeem !
