### ISSUE TITLE
Disable when certain apps are open/focused.

### ISSUE THREAD

**Issue by mikroskeem** [archagon/sensible-side-buttons#39]
This would be perfect as some games I happen to play on my Mac utilize mouse side buttons, but they won't function when SensibleSideButtons is running (as it's sending a keybinding on click).

Right now disabling SSS works, but I would like to have a built in solution.

**Comment by StephenHaney** [comment]
Also experiencing this – seems like game keybindings screens can't see the events that this creates. Would be cool to disable automatically when games are launched, or allow users to create a list of apps to ignore.

**Comment by mikroskeem** [comment]
[My fork](https://github.com/mikroskeem/sensible-side-buttons) has a workaround for Borderlands 2 though. If someone knows better how Apple stuff works (Objective-C and OS X APIs) then feel free to  borrow my code.

**Comment by bojanin** [comment]
Ill try and make a menu to let you select which applications to enables, seems like many would benefit (including myself). For anyone looking for a VSCode fix my branch has it

**Comment by minego** [comment]
This is also an issue for qutebrowser. I would love to have a solution for this.

**Comment by Kyrluckechuck** [comment]
@bojanin did you make any progress with this?

It appears this issue has been closed by OP but I don't see this being resolved at present! (Especially since last commit was 2 years ago)

**Comment by mikroskeem** [comment]
Just ignore me, closing stale issues. :)
