### ISSUE TITLE
adding "natural scroll" disable on mouse plugin

### ISSUE THREAD

**Issue by shaun-sweet** [archagon/sensible-side-buttons#5]
Anyway this can be done?  I'm a web developer and would be willing to figure this out as I use this tool for daily work.  When I go to meetings however with my laptop I do not bring my mouse and I like natural scrolling with the touch pad but standard stuff for the mouse.  Perhaps you could point me in the right direction if this is something you'd be willing to entertain a PR for but not willing to implement yourself :)

**Comment by cipri-tom** [comment]
Not to do any disfavour to this awesome software, but since they also mention it on the homepage... 
USBOverdrive. It's a freeware software which enables the kind of behaviour that you need (and every sensible person).

So yeah, use USB Overdrive in conjunction with this little very awesome tool.

**Comment by allienx** [comment]
A bit of a late response but for anyone who finds this thread:

[https://github.com/pilotmoon/Scroll-Reverser](https://github.com/pilotmoon/Scroll-Reverser)

I think this is what you're looking for.

**Comment by archagon** [comment]
Not really the right tool for the task.
