### ISSUE TITLE
behaviour is backwards on Razer Deathadder 2013 (Chroma)

### ISSUE THREAD

**Issue by eknoop** [archagon/sensible-side-buttons#6]
Back button takes me forward, forward button takes me back.

**Comment by archagon** [comment]
Hmm, strange. Well, my app only responds to M4 and M5, so your mouse must be emitting those commands backwards for some reason... maybe I could add a menu option to switch the buttons, but this seems like a very edge case.

**Comment by indrekpaas** [comment]
@eknoop I have the same mouse, but the buttons work as expected, same with regular, non-Chroma model. @archagon happy to help with debugging in some capacity.

**Comment by adlibdalom** [comment]
They're reversed for me on a Fujitsu GL9000 on macOS 10.12.6 as well.

**Comment by expiredyogurt** [comment]
same issue for me, using the deathadder non chroma edition, i think this happens when i installed the razer synape to adjust the dpi to make the mouse glide smoother and then i noticed the side buttons are switched

**Comment by criticalfiction** [comment]
Happens to me too on a cheap Belkin wireless mouse.

**Comment by pkarastelev** [comment]
Same problem here with a LogiLink ID0105. An option to reverse the buttons would be awesome.

**Comment by archagon** [comment]
I'm not sure what's going on with your guys's mouses, but I added an option to swap the buttons in v1.0.5. You can re-download the app from the main website. Let me know if anything breaks! (It should not, the change is simple.)

**Comment by criticalfiction** [comment]
That's awesome. Next Amazon purchase will go via your link.

**Comment by archagon** [comment]
Thanks! ☺️

**Comment by pkarastelev** [comment]
Awesome, thanks!
