### ISSUE TITLE
No longer working with Slack on Mac OS X

### ISSUE THREAD

**Issue by john-aws** [archagon/sensible-side-buttons#76]
SensibleSideButtons v1.0.6 Back/Forward buttons no longer work on Slack (Mac OS Monterey 12.6.5) after a recent Slack update to v4.31.156.

I'm using Logi Ergo M575 but [other reports](https://www.reddit.com/r/Slack/comments/12kq460/side_mouse_buttons_stopped_working_in_slack_app/) indicate same issue with Logi MX Master 3.

**Comment by cdzombak** [comment]
I've noticed this too. I suspect this is not a SensibleSideButtons bug; seems like a Slack bug instead.

**Comment by chrislujan** [comment]
same here. SSB is still working on my browsers and such. I'm using a Logitech MXVertical and Ventura 13.3.1

**Comment by john-aws** [comment]
Note: keyboard equivalents of Back and Forward are &#8984;+[ and &#8984;+]

**Comment by gg-hsi** [comment]
same issue here. This happened after the last Ventura update.

**Comment by chrislujan** [comment]
> same here. SSB is still working on my browsers and such. I'm using a Logitech MXVertical and Ventura 13.3.1

this seems to be fixed now, same OS version and mouse, this version of slack appears to not have this problem: Version 4.32.122

**Comment by john-aws** [comment]
@chrislujan thank you. Confirmed that this is fixed in Slack version 4.32.122 for Mac.

**Comment by vhnguyenae** [comment]
I updated to 4.32.122 but it is still not working, I have a logitech MX maxter 3 so I did a workaround by using the logi+ option to set up a shortcut `Cmd [` and `Cmd ]` as the key stroke of those back and forward button for the Slack app
