### ISSUE TITLE
Not working on Firefox 57

### ISSUE THREAD

**Issue by JulianLiu** [archagon/sensible-side-buttons#8]
Recently I'm testing Firefox 57b3, found out sensible buttons does not work on it. I'm not sure if it's just me or it's affecting everyone, and this probably is a bug in Firefox (as previous versions work fine). But both 2-finger swipe and 3-finger swipe from touchpad still work on this version of Firefox, which kind of baffling me.  I'll try to find out if there's any tweaking option in Firefox could workaround this first.

**Comment by archagon** [comment]
Hmm, that’s weird. Do the buttons work in other apps?

**Comment by JulianLiu** [comment]
Yes, other apps work fine. 
As Firefox 57 is still in beta, maybe just wait for it's final release then check again.

**Comment by archagon** [comment]
It’s very strange that regular three finger swipes work fine, but the ones
my app sends does not. Maybe FF is looking for some metadata that’s not
included in my events, hmm...

**Comment by pascalj** [comment]
Maybe you can try again: with Firefox 57.0b10 and SensibleSideButtons 1.0 it works fine for me.

**Comment by JulianLiu** [comment]
Firefox 57 final is released. Sensible-side-buttons is working fine on this release. :)
