### ISSUE TITLE
It works on perfectly everywhere except in the VS Code

### ISSUE THREAD

**Issue by lhypds** [archagon/sensible-side-buttons#86]
Mouse: SteelSeries Rival 650

Disable it  
-> Back/Forward works in VS Code  
-> Back/Forward does not work in other apps (like Finder).  

Enabled it  
-> Back/Forward does not work in VS Code  
-> Back/Forward works in other apps (like Finder).

**Comment by lhypds** [comment]
https://github.com/archagon/sensible-side-buttons/issues/81

**Comment by lhypds** [comment]
Tried install the Swipe To Navigate extension, not work...

https://github.com/archagon/sensible-side-buttons/issues/81#issuecomment-2020446382

**Comment by lhypds** [comment]
https://github.com/bojanin/sensible-side-buttons

Works for me.

**Comment by Crefok** [comment]
how did you manage to install this Version?

**Comment by jordyvandomselaar** [comment]
@lhypds is there any chance you could update your fork to also handle Cursor?
